# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2b3e8481967fad766a60879d7301a8c7fdd0a56d4bc7f680c7c8d3c70bc29235819abd158dc292c2ae05c94f352733657dd63ec7fb0fccd251aa69dcbb0813d2

test:
  secret_key_base: 048fcc32e4ea861d13cd6108e02ca4c972a65a23730a103de203219ff46cf636c31f84aea71524966081c98432a3f287a6a3de4de72072755f3ea7e5a5e3b526

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
